### ISSUE TITLE
[SETTING] 폴더 구조 변경

### ISSUE THREAD

**Issue by YoonAh-dev** [YoonAh-dev/Just-A-Guide#1]
## 💡 Issue

폴더 구조를 변경합니다.

## 📝  todo
- [x] Source 파일 생성
- [x] Global 파일 생성
- [x] Resource 파일 생성
