### ISSUE TITLE
[UI] Factory UI 구성하기

### ISSUE THREAD

**Issue by YoonAh-dev** [YoonAh-dev/Just-A-Guide#5]
## 💡 Issue

Factory 뷰에서의 UI를 구성합니다.

## 📝  todo
- [x] Navigation Bar 구성
- [x] 툴바 버튼 구성
- [x] 하단 Buttom View 설정 -> Background color 보기
- [x] 상단 Component 부분 구성
