### ISSUE TITLE
[FEAT] Factory Space 구성

### ISSUE THREAD

**Issue by YoonAh-dev** [YoonAh-dev/Just-A-Guide#8]
## 💡 Issue

Factory Space를 구성합니다.

## 📝  todo
- [x] Button Factory 구성
- [x] Slider Factory 구성
- [x] Image Factory 구성
- [x] Text Field Factory 구성
